//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS.IDS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDS.IDS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ButtonStop_Start {
            get {
                return ResourceManager.GetString("ButtonStop_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ButtonStop_Stop {
            get {
                return ResourceManager.GetString("ButtonStop_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string CarBrand {
            get {
                return ResourceManager.GetString("CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car id.
        /// </summary>
        internal static string CarId {
            get {
                return ResourceManager.GetString("CarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car type.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crate imp. map.
        /// </summary>
        internal static string CreateImportanceMap {
            get {
                return ResourceManager.GetString("CreateImportanceMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Scene.
        /// </summary>
        internal static string DayScene {
            get {
                return ResourceManager.GetString("DayScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadDb.
        /// </summary>
        internal static string LoadDb {
            get {
                return ResourceManager.GetString("LoadDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load video.
        /// </summary>
        internal static string LoadVideo {
            get {
                return ResourceManager.GetString("LoadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load videos.
        /// </summary>
        internal static string LoadVideos {
            get {
                return ResourceManager.GetString("LoadVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorries.
        /// </summary>
        internal static string Lorries {
            get {
                return ResourceManager.GetString("Lorries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDS.
        /// </summary>
        internal static string MainFrameName {
            get {
                return ResourceManager.GetString("MainFrameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string Match {
            get {
                return ResourceManager.GetString("Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Scene.
        /// </summary>
        internal static string NightScene {
            get {
                return ResourceManager.GetString("NightScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NormalizeDb.
        /// </summary>
        internal static string NormalizeDb {
            get {
                return ResourceManager.GetString("NormalizeDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string PersonalVehicles {
            get {
                return ResourceManager.GetString("PersonalVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save reference distinct.
        /// </summary>
        internal static string SaveReferenceDistinct {
            get {
                return ResourceManager.GetString("SaveReferenceDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save road settings.
        /// </summary>
        internal static string SaveRoadSettings {
            get {
                return ResourceManager.GetString("SaveRoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string SumText {
            get {
                return ResourceManager.GetString("SumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together.
        /// </summary>
        internal static string Together {
            get {
                return ResourceManager.GetString("Together", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of.
        /// </summary>
        internal static string TypeOf {
            get {
                return ResourceManager.GetString("TypeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of scene.
        /// </summary>
        internal static string TypeOfScene {
            get {
                return ResourceManager.GetString("TypeOfScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input numer  for count of roud lines.
        /// </summary>
        internal static string WrongInputNumerForCountOfRoudLines {
            get {
                return ResourceManager.GetString("WrongInputNumerForCountOfRoudLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number format for distinct.
        /// </summary>
        internal static string WrongNumberFormatForDistinct {
            get {
                return ResourceManager.GetString("WrongNumberFormatForDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 fps.
        /// </summary>
        internal static string ZeroFPS {
            get {
                return ResourceManager.GetString("ZeroFPS", resourceCulture);
            }
        }
    }
}
